name: FuchiCorp Source Code Checks!

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  source-code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/workflows/copy.yml

